export const historyCopy = {
  title: 'История',
  filter: 'Фильтр',
  search: 'Поиск',
  seeAll: 'См. все',
  filterTitle: 'Настроить фильтр',
  opTypeLabel: 'Вид операции',
  accountLabel: 'Вид счета',
  periodLabel: 'Период',
  calendarHintPick: 'Выберите дату',
  calendarHintSingleReady: 'Один день — или выберите вторую дату для периода',
  calendarHintRangeReady: 'Период выбран',
  calendarReset: 'Сбросить',
  pickDates: 'Выбрать даты',
  chipTopup: 'Пополнение',
  chipDebit: 'Списание',
  chipAll: 'Все операции',
  opTypeSheetTitle: 'Вид операции',
  actionSheetTitle: 'Операция',
  repeatOp: 'Повторить операцию',
  shareReceipt: 'Поделиться чеком',
  resetFilter: 'Сбросить фильтр',
  apply: 'Применить',
  detailsTitle: 'Детали операции',
  share: 'Поделиться',
  cancel: 'Отменить',
  help: 'Помощь',
  receipt: 'Чек',
  cancelTitle: 'Отменить операцию?',
  cancelYes: 'Да',
  cancelNo: 'Нет',
  dateOut: 'Дата вывода',
  receiptNo: 'Номер квитанции',
  payer: 'ФИО плательщика',
  fee: 'Комиссия',
  fromAccount: 'Вывод из',
  destination: 'Куда',
  status: 'Статус',
  amount: 'Сумма',
  download: 'Скачать',
  mockShare: 'Поделиться (mock)',
  mockDownload: 'Скачать (mock)',
  mockHelp: 'Помощь',
  empty: 'Нет операций',
  receiptMockNote: 'Визуальный mock. Не является фискальным чеком.',
} as const;

export const deferredHistoryCopy = {
  module: 'RECON-007',
} as const;
