/** Payment / top-up catalog copy (LOCAL_DRAFT). */

export const paymentCopy = {
  title: 'Оплата',
  searchPlaceholder: 'Что хотите пополнить?',
  categoryLabel: 'Категория',
  categoryAll: 'Все категории',
  categorySheetTitle: 'Категория',
  tabAll: 'Все',
  tabFavorites: 'Избранные',
  sectionBookmakers: 'Букмекеры',
  sectionDigital: 'Цифровые товары',
  sectionMfo: 'МФО',
  bonusTopup: 'Бонус за пополнение +2%',
  commissionPrefix: 'Комиссия за пополнение',
  emptyFavorites: 'Избранных сервисов пока нет',
  phoneNumber: 'Номер телефона',
  amountLabel: 'Сумма',
  payFrom: 'Оплатить со счёта',
  chooseAccount: 'Выберите счёт',
  bonusAccount: 'Бонусный счет',
  amountUnitTenge: 'Тенге',
  amountUnitRub: 'Рубли',
  amountUnitUsd: 'Доллары',
  amountUnitBonus: 'Бонусы',
  payCta: 'Оплатить',
  favoriteAdd: 'В избранное',
  favoriteRemove: 'Убрать из избранного',
  paySuccess: 'Пополнение принято (LOCAL_DRAFT).',
  serviceNotFound: 'Сервис не найден',
} as const;
