/** Withdrawal copy. Card-select strings are LOCAL_DRAFT (clear UX). Phone/cash still carry legacy typos. */

export const withdrawCopy = {
  methodTitle: 'Способ вывода',
  card: 'Карта',
  phone: 'Баланс телефона',
  cashhelloUser: 'Пользователю Cashhello',
  cash: 'Снять в кассе наличными',
  other: 'Другое',
  otherBody: 'Continuation UNKNOWN in late UI — no payment rail invented.',
  chooseCard: 'Вывод на карту',
  chooseCardSupport: 'Введите номер карты или отсканируйте её камерой',
  choosePhone: 'Вывод на баланс телефона',
  choosePhoneSupport: 'Введите номер телефона',
  chooseCashhelloUser: 'Пользователю Cashhello',
  chooseCashhelloUserSupport: 'Введите номер телефона получателя',
  userNotFound: 'Пользователь не найден',
  fromAccount: 'Счёт списания',
  chooseAccount: 'Выберите счёт',
  bonusAccount: 'Бонусный счет',
  phoneTitle: 'Вывод на баланс',
  chooseKassa: 'Выбрать кассу',
  title: 'Вывод денег',
  from: 'Откуда',
  to: 'Куда',
  choose: 'Выбрать',
  continue: 'Продолжить',
  transfer: 'Перевести',
  all: 'Все',
  amountRange: 'Сумма (от 1000₸ до 1970₸)',
  overLimit: 'Сумма превышает допустимую: 1970₸',
  fee: 'Комиссия: 30 ₸',
  feeInline: 'Комиссия 30₸',
  cardNumber: 'Номер карты',
  amountLabel: 'Сумма',
  amountUnitTenge: 'Тенге',
  amountUnitRub: 'Рубли',
  amountUnitUsd: 'Доллары',
  amountUnitBonus: 'Бонусы',
  phoneNumber: 'Номер телефона',
  phoneMask: '+7 (___) ___ __ __',
  pickContact: 'Контакты',
  cards: 'Карты',
  savedCardsTitle: 'Сохранённые карты',
  savedCardButton: 'Сохранённая карта',
  savedCardModalTitle: 'Сохранённые карты',
  savedCardModalBody:
    'Пока сохранённых карт нет. После успешного вывода мы сохраним эту карту — в следующий раз выбрать её будет проще.',
  savedCardModalOk: 'Понятно',
  savedCardPick: 'Выбрать карту',
  savedPhonesButton: 'Сохранённые телефоны',
  savedPhonesModalTitle: 'Сохранённые телефоны',
  addresses: 'Адреса',
  /** Legacy typo strings kept for unreworked cash screens. */
  savedCards: 'Пока у вас нет сохнаренных карт, после вывода мы схраним её.',
  savedCardsEmpty:
    'Сохранённых карт пока нет. После первого вывода карта появится здесь — в следующий раз выбрать будет проще.',
  savedNumbers: 'Пока у вас нет сохнаренных номеров, после вывода мы схраним их.',
  savedAddresses: 'Пока у вас нет сохнаренных адресов, после вывода мы схраним их.',
  searchAddress: 'Поиск адреса',
  search: 'Поиск',
  open: 'Открыто',
  nearby: 'Рядом',
  roundClock: 'Круглосуточно',
  holdCard: 'Держите карту внутри рамки',
  scanCard: 'Сканировать карту',
  cancel: 'Отмена',
  confirmTitle: 'Подтверждение',
  confirmCta: 'Подтвердить',
  processing: 'Обработка....',
  done: 'Готово',
  failed: 'Что-то пошло не так',
  receiptInfo: 'Информация',
  receiptOpType: 'Тип операции',
  receiptOpTypeValue: 'Вывод на карту',
  receiptOpTypePhone: 'Вывод на баланс телефона',
  receiptOpTypeUser: 'Перевод пользователю Cashhello',
  receiptService: 'Сервис',
  receiptServiceValue: 'Вывод на банковскую карту',
  receiptServicePhone: 'Пополнение баланса телефона',
  receiptServiceUser: 'Перевод пользователю Cashhello',
  receiptCard: 'Карта',
  receiptPhone: 'Телефон',
  receiptRecipient: 'Получатель',
  receiptFrom: 'Счёт списания',
  receiptAmount: 'Сумма',
  receiptDate: 'Дата',
  receiptStatus: 'Статус',
  receiptFee: 'Комиссия',
  receiptSuccess: 'Успешно',
  share: 'Поделиться',
  shareMock: 'Чек скопирован (mock)',
  withdrawAmount: (n: string) => `Вывести ${n}`,
  homeCta: 'Вывести деньги',
} as const;

export const deferredWithdrawCopy = {
  title: 'Вывести деньги',
  module: 'RECON-006',
  body: 'Withdrawal reconstructed as MOCK STATE ONLY. No bank payout, telecom, cash-desk API, or ledger.',
} as const;
