/** Exact visible late-UI copy from live Figma money-in cluster. Do not polish typos. */

export const topupCopy = {
  methodTitle: 'Способ пополнения',
  betweenAccounts: 'Между счетами',
  otherBankCard: 'Картой другого банка',
  cashDesk: 'Пополнить в кассе наличными',
  topUp: 'Пополнить',
  topUpAmount: (amount: string) => `Пополнить ${amount}`,
  betweenSupport: 'Выберите счета и сумму перевода',
  cardSupport: 'Введите номер карты или выберите сохранённую',
  funding: 'Пополнение',
  from: 'Откуда',
  to: 'Куда',
  choose: 'Выбрать',
  chooseAccount: 'Выберите счёт',
  chooseCurrency: 'Выберите валюту',
  kzt: 'KZT',
  usd: 'USD',
  amountLabel: 'Сумма',
  amountRange: '(от 1000₸ до 1970₸)',
  all: 'Все',
  fxSource: 'НБ РК',
  willCredit: (amount: string) => `К зачислению: ${amount}`,
  fxAsOf: (date: string) => `курс на ${date}`,
  cardNumber: 'Номер карты',
  expiry: 'мм/гг',
  cvv: 'cvv/cvc',
  cards: 'Карты',
  savedCardButton: 'Сохранённая карта',
  savedCardModalTitle: 'Сохранённые карты',
  savedCards: 'Пока у вас нет сохнаренных карт, после вывода мы схраним её.',
  chooseKassa: 'Выбрать кассу',
  searchAddress: 'Пойск адреса',
  addresses: 'Адреса',
  savedAddresses: 'Пока у вас нет сохнаренных адресов, после вывода мы схраним их.',
  search: 'Поиск',
  open: 'Открыто',
  nearby: 'Рядом',
  roundClock: 'Круглосуточно',
  holdCard: 'Держите карту внутри рамки',
  cancel: 'Отмена',
  demoFx: 'LEGACY DESIGN DISPLAY / MOCK',
} as const;

export const topUpBridgeCopy = {
  title: 'Пополнение',
  module: 'RECON-005',
  body: 'Top-up / Between own accounts / External card / Cash reconstructed as MOCK STATE ONLY. No ledger, FX engine, card processor, or cash-desk API.',
} as const;
