/** Exact visible late-UI copy from live Figma (RECON-009). Preserve typos. */

export const profileCopy = {
  personalRow: 'Личный данные',
  settingsSection: 'Настройки',
  pushNotifications: 'Push-уведомления',
  fingerprintLogin: 'Вход по отпечатку пальца',
  changePin: 'Изменить PIN-код входа',
  documents: 'Документы',
  documentsStub: 'Раздел документов — LOCAL_DRAFT stub.',
  changePhone: 'Изменить номер телефона',
  linkedCards: 'Привязанные карты',
  supportService: 'Служба поддержки',
  suggestIdea: 'Предложить идею',
  logout: 'Выйти',
  deleteAccount: 'Удалить профиль',
  sessionSection: 'Сессия',
  sessionSupport: 'Вы можете выйти из кабинета или удалить профиль.',
  statusEyebrow: 'ВАШ СТАТУС',
  statusUnidentified: 'Неидентифицированный',
  statusProgress: '25%',
  statusHint: 'Чтобы увеличить лимиты, совершать переводы и вывод средств',
  statusMore: 'Подробнее',
  statusDetailTitle: 'Неидентифицированный пользователь',
  statusDetailBadge: 'Ваш статус',
  standardLimitsTitle: 'Стандартные лимиты',
  limitSingleTx: 'Максимальная сумма одной транзакции',
  limitStorage: 'Максимальная сумма хранения',
  limitDaily: 'На общую сумму транзакций в сутки',
  limitAmount: '12 975 ₸',
  limitLawNote: 'Ограничения установлены согласно Закону РК № 11-VI',
  lockedTransfers: 'Переводы между кошельками',
  lockedAbroad: 'Отправка денег за границу',
  lockedWithdraw: 'Вывод средств',
  lockedPayments: 'Полный доступ к платежным сервисам',
  ageBadge: '18+',
  lockedHint:
    'Эти возможности станут доступны после прохождения идентификации в приложении. Нерезидентам необходимо обратиться в офис Cashhello. Для отдельных операций требуется достижение 18 или 21 года.',
  lockedMore: 'Подробнее →',
  expandLimits: 'Расширить лимиты',
  expandLimitsStub: 'Идентификация для расширения лимитов — LOCAL_DRAFT stub.',
  promoPlaceholder: 'Введите промокод',
  promoApply: 'Применить',
  promoApplied: 'Промокод принят (demo).',
  promoEmpty: 'Введите промокод.',
  personalTitle: 'Личные данные',
  fioLabel: 'ФИО',
  documentLabel: 'Номер документа',
  birthLabel: 'Дата рождения',
  personalHint: 'Для изменения личных данных нужно пройти проверку',
  change: 'Изменить',
  phoneTitle: 'Новый номер телефона',
  phoneLabel: 'Телефон',
  phoneMask: '+7 (___) ___ __ __',
  smsTitle: 'Введите код из СМС',
  smsResend: 'Получить новый код через 00:34',
  notificationsTitle: 'Уведомления',
  filter: 'Фильтр',
  helpAction: 'Помощь',
  helpTitle: 'Помощь',
  helpDescription: 'Описание ошибки',
  attachDocument: 'Прикрепить документ',
  pinCreateTitle: 'Придумайте код доступа',
  pinCreateSupport: 'Используется для входа в приложение',
  pinRepeatTitle: 'Повторите код доступа',
  pinRepeatSupport: 'Используется для входа в приложение',
  pinErrorMessage: 'Код доступа не совпадают',
  filterUnavailable: 'Фильтр уведомлений — отдельный экран в late UI не найден.',
  personalChangeUnavailable: 'Изменение личных данных требует проверки. Mock only.',
  attachUnavailable: 'Прикрепление документа — mock only. Backend отсутствует.',
  linkedCardsStub: 'Список привязанных карт — LOCAL_DRAFT stub.',
  suggestIdeaStub: 'Форма предложения идеи — LOCAL_DRAFT stub.',
  logoutConfirmTitle: 'Выйти',
  logoutConfirmBody: 'Выйти в режим без авторизации? Финансовое состояние прототипа не сбрасывается.',
  logoutConfirmAction: 'Выйти',
  logoutCancel: 'Отмена',
  deleteConfirmTitle: 'Удалить профиль',
  deleteConfirmBody: 'Профиль будет удалён в демо-режиме. Вернуться к экрану входа?',
  deleteConfirmAction: 'Удалить',
  demoNote: 'DEMO / NOT REAL PERSONAL DATA',
} as const;
